HumanResourceManagementSystem/HumanResourceManagementSystem/Models/Leave.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        public int LeaveId { get; set; }
        public string Subject { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public long EmployeeId { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumanResourceManagementSystem.Models;
using Newtonsoft.Json;

namespace HumanResourceManagementSystem.Controllers
{
    public class LeaveController : Controller
    {
        private HumanResourceManagementSystemEntities db = new HumanResourceManagementSystemEntities();

        // GET: Leave
        public ActionResult Index()
        {
            if (Session["AdminId"] != null)
            {

                var leave = db.Leave.Include(l => l.Employee);
                return View(leave.ToList());
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }
        [HttpGet]
        public ActionResult List()
        {
            var list = db.Leave.ToList();

            return View(list);
        }

        //printing and filter
        public JsonResult Getdata(string data)
        {
            var list = db.Leave.ToList();
            return Json(list);
        }
        public JsonResult existLeave(long userdata)
        {
            System.Threading.Thread.Sleep(200);
            Leave SearchData = db.Leave.Where(x => (x.Date.Value.Day == DateTime.Now.Day) || (x.EmployeeId == userdata)).SingleOrDefault();
            //Leave SearchData = db.Leave.Where(x => x.EmployeeId == userdata).SingleOrDefault();
            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }

        // GET: Leave/Details/5
        public ActionResult Details(int? id)
        {

            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Leave leave = db.Leave.Find(id);
                if (leave == null)
                {
                    return HttpNotFound();
                }
                return View(leave);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // GET: Leave/Create
        public ActionResult Create()
        {
                ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username");
                return View();
        }

        // POST: Leave/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LeaveId,Subject,Date,Description,Status,EmployeeId")] Leave leave )
        {
            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //if (leave.Date.Value.Day == DateTime.Now.Day) return HttpNotFound("Too late or too early");
            var hasAttendance = db.Leave.Where(i => i.EmployeeId == leave.EmployeeId && i.Date.Value.Day == leave.Date.Value.Day&& i.Date.Value.Month == leave.Date.Value.Month && i.Date.Value.Year == leave.Date.Value.Year).FirstOrDefault();
            if (hasAttendance!=null)
            {
                ViewBag.Massage = "you are already Apply for Leave, You cannot Apply More";
            }
            else
            {
                try
                {
                    db.Leave.Add(leave);
                    db.SaveChanges();
                    return RedirectToAction("LeaveInformation");
                }
                catch (Exception ex)
                {

                    return HttpNotFound(ex.Message);
                }
            }
#pragma warning disable CS0162 // Unreachable code detected
            ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", leave.EmployeeId);
#pragma warning restore CS0162 // Unreachable code detected
            return View(leave);
            
        }

        // GET: Leave/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Leave leave = db.Leave.Find(id);
                if (leave == null)
                {
                    return HttpNotFound();
                }
                ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", leave.EmployeeId);
                return View(leave);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: Leave/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LeaveId,Subject,Date,Description,Status,EmployeeId")] Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leave).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", leave.EmployeeId);
            return View(leave);
        }

        // GET: Leave/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Leave leave = db.Leave.Find(id);
                if (leave == null)
                {
                    return HttpNotFound();
                }
                return View(leave);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: Leave/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Leave leave = db.Leave.Find(id);
            db.Leave.Remove(leave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult LeaveInformation()
        {
            if (Session["UserId"] != null)
            {
                long empid = (long)Session["UniqueId"];
                return View(db.Leave.Where(x => x.EmployeeId == empid).ToList());
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/Create.cshtml
@model HumanResourceManagementSystem.Models.Leave

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
}
<link href="~/css/editform.css" rel="stylesheet" />
<style>
    .status {
        display: none;
    }
</style>
<div class="main-content">
    <div class="container-fluid content-top-gap">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Leave/Index" style="color:darkblue">Leaves</a></li>
                <li class="breadcrumb-item active" aria-current="page">Adding-Leave</li>
            </ol>
        </nav>
    </div>
    <div class="form-block">
        <h2>Adding Leave</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <section class="contact-form">
                <div class="container">
                    <div class="contacts12-main">
                        <!-- ........... form ..................-->
                        <form action="" method="post" class="form">
                            <div class="main-input">
                                <div>
                                    @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DropDownList("EmployeeId", null, "-- Please select --", new
                                    {
                                        @class = "contact-input",
                                        @required = "required",
                                        @id = "EmployeeId",
                                        @onchange = "UserCheck()"
                                    })
                                    <p id="Status"></p>
                                    @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="text" name="Subject" id="Subject" placeholder=" Leave Subject" class="contact-input"
                                           data-val="true" data-val-required="Department Name is Blank" data-val-regex-pattern="^[a-zA-Z ]{5,30}$" data-val-regex="Please Enter Valid Department Name" data-val-minlength-min="5"
                                           data-val-minlength="Department Name is Too Small" data-val-maxlength-max="30" data-val-maxlength="Department Name is Too Large" />
                                    @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                                </div>
                                <div class="input-icon position-relative">
                                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="date" name="Date" id="today" placeholder="" readonly
                                           class="contact-input" required />
                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="status">
                                <label style="font-size: 14px medium; font-weight: 600; ">Cancel  : </label>
                                @Html.RadioButtonFor(m => m.Status, "Cancel", new { @readonly = "readonly" })&nbsp;&nbsp;&nbsp;&nbsp;
                                <label style="font-size: 14px medium; font-weight: 600;">Pending :</label>
                                @Html.RadioButtonFor(m => m.Status, "Pending", new { @checked = "true", @readonly = "readonly" })&nbsp;&nbsp;&nbsp;&nbsp;
                                <label style="font-size:14px medium; font-weight:600;">Approved :</label>
                                @Html.RadioButtonFor(m => m.Status, "Approved", new { @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <textarea class="contact-textarea" name="Description" id="Description"
                                      placeholder="Type Event Description here" data-val="true" data-val-required="Department Description is Blank" data-val-regex-pattern="^[#.0-9a-zA-Z\s,-]+$"
                                      data-val-regex="Please Enter Valid Department Description" data-val-minlength-min="20" data-val-minlength="Department Description is Too Small"
                                      data-val-maxlength-max="225" data-val-maxlength="Department Description is Too Large"></textarea>
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Aply for Leave" class="btn btn-default" />
                                    @*<i class="fa fa-arrow-circle-o-left">&nbsp;@Html.ActionLink("Back to Admin", "Index")</i>*@
                                    <i class="fa fa-arrow-circle-o-left">&nbsp;@Html.ActionLink("Click to Leave List", "LeaveInformation", "Employee")</i>
                                </div>
                                <label id="leaveerror" type="hidden" style="color:red " contextmenu=""> </label>
                            </div>
                        </form>
                        <!--      --------------//................form.................. -->
                    </div>
                </div>
            </section>
        }
        @if (ViewBag.Massage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Massage")
                };
            </script>
        }
    </div>
</div>
@*<script>
       function UserCheck() {
           $("#Status").html("Checking.........!");
           $.post("@Url.Action("existLeave", "Leave")",
               {
                   userdata: $("#EmployeeId").val()
               },
               function (data) {
                   if (data == 0) {
                       $("#Status").html('<font color="Green">User ID Available......!</font>');
                       $("#EmployeeId").css("border-color", "Green");
                   }
                   else {
                       $("#Status").html('<font color="Red"> That User ID already Add......!</font>');
                       $("#EmployeeId").css("border-color", "red");
                   }
               });
        }
</script>*@
<script>
    document.getElementById('today').value = new Date().toISOString().slice(0, 10);
</script>

@section Validation {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/Delete.cshtml
@model HumanResourceManagementSystem.Models.Leave

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/deleteemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Leave/Index" style="color:darkblue">Leaves</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete-Leave</li>
            </ol>
        </nav>

    </div>

    <div class="dl-horizontal">

        <h2>Delete Leave</h2>

        <h3>Are you sure you want to delete this?</h3>


        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Employee.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Subject)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Subject)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                <i class="fa fa-arrow-circle-o-left">@Html.ActionLink("Back to List", "Index")</i>
            </div>
        }
    </div>
    
 </div>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/Details.cshtml
@model HumanResourceManagementSystem.Models.Leave

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css/detailemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Leave/index" style="color:darkblue">Leaves</a></li>
                <li class="breadcrumb-item active" aria-current="page">Detail-Leave</li>
            </ol>
        </nav>

    </div>

    <div class="dl-horizontal">
        <h2>Leave Details</h2>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Employee.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Subject)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Subject)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

        </dl>
        <p class="btn-default">
            <i class="fa fa-pencil-square-o"> &nbsp;@Html.ActionLink("Edit", "Edit", new { id = Model.LeaveId })</i>
            <i class="fa fa-arrow-circle-o-left">&nbsp; @Html.ActionLink("Back to List", "Index")</i>
        </p>

    </div>
  </div>  

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/Edit.cshtml
@model HumanResourceManagementSystem.Models.Leave

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/editform.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Leave/Index" style="color:darkblue">Leaves</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit-Leave</li>
            </ol>
        </nav>
    </div>
    <div class="form-block">
        <h2>Edit Leave Information</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.LeaveId)
            <div class="container">
                <div class="contacts12-main">
                    <div class="main-input ">
                        <div>
                            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "contact-input", @required = "Required" })
                            @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "contact-input", @required = "Required" } })
                            @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "contact-input", @required = "Required", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div>
                        <label style="font-size: 14px medium; font-weight: 600; ">Cancel  : </label>
                        @Html.RadioButtonFor(m => m.Status, "Cancel")&nbsp;&nbsp;&nbsp;&nbsp;
                        <label style="font-size: 14px medium; font-weight: 600; ">Pending :</label>
                        @Html.RadioButtonFor(m => m.Status, "Pending" @*new { @checked = "true" }*@)&nbsp;&nbsp;&nbsp;&nbsp;
                        <label style="font-size:14px medium; font-weight:600;">Approved :</label>
                        @Html.RadioButtonFor(m => m.Status, "Approved")
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "contact-textarea", @Required = "Required" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                            <i class="fa fa-arrow-circle-o-left">&nbsp; @Html.ActionLink("Back to List", "Index")</i>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@section Validation {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/Index.cshtml
@model IEnumerable<HumanResourceManagementSystem.Models.Leave>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/employeeindex.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="#" style="color:darkblue">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Leaves-List</li>
            </ol>
        </nav>

    </div>
    <div class="info">
        <h2>Leaves Information List</h2>
        <div style="height: auto; overflow-y: scroll">
            <a href="~/Leave/List" style="padding:10px; color:blue;" class="report">Generate Report<i class="fa fa-arrow-right"></i></a>

            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Employee.username)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Employee.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td style="padding: 25px 20px; ">
                            <i class="Statustrue"> @Html.DisplayFor(modelItem => item.Status)</i>
                        </td>
                        <td>
                            @Html.ActionLink(".", "Edit", new { id = item.LeaveId }, new { @class = " fa fa-pencil" })
                            @Html.ActionLink(".", "Details", new { id = item.LeaveId }, new { @class = " fa fa-eye" })
                            @Html.ActionLink(".", "Delete", new { id = item.LeaveId }, new { @class = " fa fa-trash" })
                        </td>
                    </tr>
                }

            </table>
            <a href="~/Leave/List" style="padding:10px; color:blue;" class="report">Generate Report<i class="fa fa-arrow-right"></i></a>

        </div>
    </div>
</div>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Leave/LeaveInformation.cshtml
@model IEnumerable<HumanResourceManagementSystem.Models.Leave>

@{
    ViewBag.Title = "LeaveInformation";
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
}
<link href="~/css/employeeindex.css" rel="stylesheet" />
<div class="main-content p-5">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Employee/Dashboard" style="color:darkblue">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Leaves-List</li>
            </ol>
        </nav>

    </div>
    <div class="info">
        <h2>Leaves Information List</h2>
        <div style="height: auto; overflow-y: scroll">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Employee.username)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Employee.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Subject)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td style="padding: 25px 20px; ">
                            <i class="Statustrue"> @Html.DisplayFor(modelItem => item.Status)</i>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>