HumanResourceManagementSystem/HumanResourceManagementSystem/Models/Salary.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourceManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salary
    {
        public int SalaryId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Date { get; set; }
        public string RemaningSalary { get; set; }
        public long EmployeeId { get; set; }
        public string TotalSalary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Controllers/SalariesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumanResourceManagementSystem.Models;

namespace HumanResourceManagementSystem.Controllers
{
    public class SalariesController : Controller
    {
        private HumanResourceManagementSystemEntities db = new HumanResourceManagementSystemEntities();

        // GET: Salaries
        public ActionResult Index()
        {
            if (Session["AdminId"] != null)
            {
                var salary = db.Salary.Include(s => s.Employee);
                return View(salary.ToList());
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        [HttpGet]
        public ActionResult List()
        {
            var list = db.Salary.ToList();

            return View(list);
        }

        //printing and filter
        public JsonResult Getdata(string data)
        {
            var list = db.Salary.ToList();
            return Json(list);
        }
        // GET: Salaries/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Salary salary = db.Salary.Find(id);
                if (salary == null)
                {
                    return HttpNotFound();
                }
                return View(salary);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // GET: Salaries/Create
        public ActionResult Create()
        {
            if (Session["AdminId"] != null)
            {
                ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username");
                ViewBag.TotalSalary = new SelectList(db.Employee, "EmployeeId", "EmpSalary");
                return View();
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: Salaries/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SalaryId,Date,TotalSalary,UserName,RemaningSalary,EmployeeId,UserName")] Salary salary)
        {
            var hasAttendance = db.Salary.Where(i => i.EmployeeId == salary.EmployeeId && i.Date.Value.Month == salary.Date.Value.Month && i.Date.Value.Year == salary.Date.Value.Year).FirstOrDefault();
            if (hasAttendance != null)
            {
                ViewBag.Massage = "your Salary Already Done, You cannot Add More";
            }
            else
            {
                try
                {
                    db.Salary.Add(salary);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {

                    return HttpNotFound(ex.Message);
                }
            }
#pragma warning disable CS0162 // Unreachable code detected
            ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", salary.EmployeeId);
#pragma warning restore CS0162 // Unreachable code detected
            ViewBag.TotalSalary = new SelectList(db.Employee, "EmployeeId", "EmpSalary", salary.EmployeeId);
            return View(salary);
        }

        // GET: Salaries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Salary salary = db.Salary.Find(id);
                if (salary == null)
                {
                    return HttpNotFound();
                }
                ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", salary.EmployeeId);
                ViewBag.TotalSalary = new SelectList(db.Employee, "EmployeeId", "EmpSalary", salary.EmployeeId);
                return View(salary);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: Salaries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SalaryId,Date,TotalSalary,RemaningSalary,EmployeeId")] Salary salary)
        {
            if (ModelState.IsValid)
            {
                db.Entry(salary).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.EmployeeId = new SelectList(db.Employee, "EmployeeId", "username", salary.EmployeeId);
            ViewBag.TotalSalary = new SelectList(db.Employee, "EmployeeId", "EmpSalary", salary.EmployeeId);
            return View(salary);
        }

        // GET: Salaries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Salary salary = db.Salary.Find(id);
                if (salary == null)
                {
                    return HttpNotFound();
                }
                return View(salary);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: Salaries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Salary salary = db.Salary.Find(id);
            db.Salary.Remove(salary);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/Create.cshtml
@model HumanResourceManagementSystem.Models.Salary

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/editform.css" rel="stylesheet" />

<div class="main-content">
    <div class="container-fluid content-top-gap">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Salaries/Index" style="color:darkblue">Salaies</a></li>
                <li class="breadcrumb-item active" aria-current="page">Adding-Salary</li>
            </ol>
        </nav>
    </div>
    <div class="form-block">
        <h2>Adding Salary</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <section>
                <div class="container">
                    <div class="contacts12-main">
                        <!--............ form ..............-->
                        <form action="" method="post" class="form">
                            <div class="main-input2">
                                <div>
                                    @Html.LabelFor(model => model.EmployeeId, "User Name", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DropDownList("EmployeeId", null, "-- Please select --", new
                                    {
                                        @class = "contact-input",
                                        @required = "required",
                                    @id = "EmployeeId",
                                        @onchange = "UserCheck()"
                                    })
                                    <p id="Status"></p>
                                    @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="Date" name="Date" id="today" placeholder="" class="contact-input" readonly
                                           required />
                                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="main-input2">
                                <div>
                                    @Html.LabelFor(model => model.TotalSalary, "Total Salary", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DropDownList("TotalSalary", null, "...Compare Sequences with User ID...", new
                                    {
                                        @class = "contact-input",
                                        @required = "required",
                                   @id = "TotalSalary",
                                        @onchange = "Check()"
                                    })
                                    <p id="SalCheck"></p>
                                    @Html.ValidationMessageFor(model => model.TotalSalary, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.RemaningSalary, "Remaning Salary", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="number" name="RemaningSalary" id="RemaningSalary" placeholder="Remaning Salary" class="contact-input" value="0" min="0" max="500000" />
                                    @Html.ValidationMessageFor(model => model.RemaningSalary, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Add Salary" class="btn btn-default" />
                                    <i class="fa fa-arrow-circle-o-left">&nbsp;@Html.ActionLink("Back to List", "Index")</i>
                                </div>
                            </div>
                        </form>
                        <!-- //................. form................. -->
                    </div>
                </div>
            </section>
        }
        @if (ViewBag.Massage != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("@ViewBag.Massage")
                };
            </script>
        }
    </div>
</div>
<!-- //................. Exit User ID................. -->
@*<script>
       function UserCheck() {
           $("#Status").html("Checking.........!");
           $.post("@Url.Action("exitInput", "Salaries")",
               {
                   userdata: $("#EmployeeId").val()
               },
               function (data) {

                   if (data == 0) {
                       $("#Status").html('<font color="Green">User ID Available......!</font>');
                       $("#EmployeeId").css("border-color", "Green");
                   }
                   else {
                       $("#Status").html('<font color="Red"> That User ID already Add......!</font>');
                       $("#EmployeeId").css("border-color", "red");
                   }
               });
        }
</script>*@

<!-- //................. Exit User Salary................. -->
@*<script>
        function Check() {
            $("#SalCheck").html("Checking.........!");
            $.post("@Url.Action("exitInput", "Salaries")",
                {
                    userdata: $("#EmployeeId").val()
                },
                function (data) {

                    if (data == 0) {
                        $("#SalCheck").html('<font color="Green">Salary Available......!</font>');
                        $("#TotalSalary").css("border-color", "Green");
                    }
                    else {
                        $("#SalCheck").html('<font color="Red"> That Salary already Add......!</font>');
                        $("#TotalSalary").css("border-color", "red");
                    }
                });
        }
</script>*@
<script>
    document.getElementById('today').value = new Date().toISOString().slice(0, 10);
</script>
@section Validation {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/Delete.cshtml
@model HumanResourceManagementSystem.Models.Salary

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/deleteemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Salaries/Index" style="color:darkblue">Salaries</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete-Salary</li>
            </ol>
        </nav>

    </div>

    <div class="dl-horizontal">

        <h2>Delete Salary</h2>
        <h3>Are you sure you want to delete this?</h3>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Employee.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Employee.EmpSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.EmpSalary)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RemaningSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RemaningSalary)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                <i class="fa fa-arrow-circle-o-left">@Html.ActionLink("Back to List", "Index")</i>
            </div>
        }
    </div>
</div>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/Details.cshtml
@model HumanResourceManagementSystem.Models.Salary

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css/detailemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Salaries/Index" style="color:darkblue">Salaries</a></li>
                <li class="breadcrumb-item active" aria-current="page">Detail-Salary</li>
            </ol>
        </nav>

    </div>

    <div class="dl-horizontal">
        <h2>Salary Details</h2>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.Employee.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Employee.EmpSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Employee.EmpSalary)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RemaningSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RemaningSalary)
            </dd>
        </dl>
        <p class="btn-default">
            <i class="fa fa-pencil-square-o"> &nbsp;@Html.ActionLink("Edit", "Edit", new { id = Model.SalaryId })</i>
            <i class="fa fa-arrow-circle-o-left">&nbsp; @Html.ActionLink("Back to List", "Index")</i>
        </p>
    </div>
</div>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/Edit.cshtml
@model HumanResourceManagementSystem.Models.Salary

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/editform.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Salaries/Index" style="color:darkblue">Salaries</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit-Salary</li>
            </ol>
        </nav>
    </div>
    <div>
        <h2>Edit Salary Information</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.SalaryId)
            <div class="container">
                <div class="contacts12-main">
                    <div class="main-input2 ">

                        <div>
                            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "contact-input", @required = "Required" })
                            @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "contact-input", @required = "Required", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="main-input2">
                        <div>
                            @Html.LabelFor(model => model.TotalSalary, "Total Salary", htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.DropDownList("TotalSalary", null, htmlAttributes: new { @class = "contact-input", @required = "required" })
                            @Html.ValidationMessageFor(model => model.TotalSalary, "", new { @class = "text-danger" })
                        </div>

                        <div>
                            @Html.LabelFor(model => model.RemaningSalary, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.RemaningSalary, new { htmlAttributes = new { @class = "contact-input" } })
                            @Html.ValidationMessageFor(model => model.RemaningSalary, "", new { @class = "text-danger" })
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Update" class="btn btn-default" />
                            <i class="fa fa-arrow-circle-o-left">&nbsp; @Html.ActionLink("Back to List", "Index")</i>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>
<script>
    document.getElementById('today').value = new Date().toISOString().slice(0, 10);
</script>
@section Validation {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/Index.cshtml
@model IEnumerable<HumanResourceManagementSystem.Models.Salary>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/employeeindex.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Admin/Dashboard" style="color:darkblue">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Salary-List</li>
            </ol>
        </nav>

    </div>
    <div class="info">
        <h2>Salaries Information List</h2>
        <div style="height: auto; overflow-y: scroll">
            <a href="~/Salaries/List" style="padding: 10px; color: blue;" class="report">Generate Report<i class="fa fa-arrow-right"></i></a>
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Employee.username)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Employee.EmpSalary)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.RemaningSalary)
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Employee.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Date)
                        </td>
                        <th>
                            @Html.DisplayFor(modelItem => item.Employee.EmpSalary)
                        </th>
                        <td>
                            @Html.DisplayFor(modelItem => item.RemaningSalary)
                        </td>

                        <td>
                            @Html.ActionLink(".", "Edit", new { id = item.SalaryId }, new { @class = " fa fa-pencil" })
                            @Html.ActionLink(".", "Details", new { id = item.SalaryId }, new { @class = " fa fa-eye" })
                            @Html.ActionLink(".", "Delete", new { id = item.SalaryId }, new { @class = " fa fa-trash" })
                        </td>
                    </tr>
                }

            </table>
            <a href="~/Salaries/List" style="padding: 10px; color: blue;" class="report">Generate Report<i class="fa fa-arrow-right"></i></a>
        </div>
    </div>
</div>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/Salaries/List.cshtml
@model IEnumerable<HumanResourceManagementSystem.Models.Salary>
@{
    ViewBag.Title = "List";
    Layout = null;

}

<link href="~/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/css/buttons.dataTables.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<script src="~/js/jsprint/jquery-3.5.1.js"></script>
<script src="~/js/jsprint/jquery.dataTables.min.js"></script>
<script src="~/js/jsprint/dataTables.buttons.min.js"></script>
<script src="~/js/jsprint/jszip.min.js"></script>
<script src="~/js/jsprint/pdfmake.min.js"></script>
<script src="~/js/jsprint/vfs_fonts.js"></script>
<script src="~/js/jsprint/buttons.html5.min.js"></script>
<script src="~/js/jsprint/buttons.print.min.js"></script>
<div class="display-2">
    <h2 style=" font-size: 50px; text-align: center;">Employee Salary List </h2>
    <table id="SalaryTable" style="width:95%" class="table table-responsive">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Employee.username)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Employee.EmpSalary)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RemaningSalary)
                </th>


            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.EmpSalary)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RemaningSalary)
                    </td>
                </tr>
            }
        </tbody>

    </table>


    <script>
        $(document).ready(function () {
            $('#SalaryTable').DataTable({
                pageLength: 10,
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        text: '<i class="fa fa-files-o"></i> Copy',
                        title: 'Alfa Employee Salary List'
                    },
                    {
                        extend: 'excelHtml5',
                        text: '<i class="fa fa-file-excel-o"></i> Excel',
                        filename: function () {
                            var d = new Date();
                            var n = d.getTime();
                            return 'AlfaOrigin' + n;
                        },
                        title: 'Alfa Employee Salary List'
                    },

                    {
                        extend: 'pdfHtml5',
                        text: '<i class="fa fa-file-pdf-o"></i> PDF',
                        filename: function () {
                            var d = new Date();
                            var n = d.getTime();
                            return 'AlfaOrigin' + n;
                        },
                        title: 'Alfa Employee Salary List'
                    },
                    {
                        extend: 'print',
                        text: '<i class="fa fa-print"></i> Print',
                        filename: function () {
                            var d = new Date();
                            var n = d.getTime();
                            return 'AlfaOrigin' + n;
                        },
                        title: 'Alfa Employee Salary List'
                    },
                ]
            });
        });
    </script>
</div>