HumanResourceManagementSystem/HumanResourceManagementSystem/Controllers/EmployeesManagmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HumanResourceManagementSystem.Models;

namespace HumanResourceManagementSystem.Controllers
{
    public class EmployeesManagmentController : Controller
    {
        private HumanResourceManagementSystemEntities db = new HumanResourceManagementSystemEntities();

        // GET: EmployeesManagment
        public ActionResult Index()
        {
            if (Session["AdminId"] != null)
            {
                var employee = db.Employee.Include(e => e.Department);
                return View(employee.ToList());
            }
            else
            {
                return HttpNotFound("Please Login Your Account and  Try Again");
            }
        }
        [HttpGet]
        public ActionResult List()
        {
            var list = db.Employee.ToList();

            return View(list);
        }

        //printing and filter
        public JsonResult Getdata(string data) {
            var list = db.Employee.ToList();
            return Json(list);
        }

        // GET: Email/Exist
        public JsonResult Checkexist(string userdata)
        {
            System.Threading.Thread.Sleep(200);
            Employee SearchData = db.Employee.Where(x => x.Password == userdata).SingleOrDefault();
            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }
        
        public JsonResult Exsitinput(string mobiledata)
        {
            System.Threading.Thread.Sleep(200);
            Employee SearchData = db.Employee.Where(x => x.Mobile == mobiledata).SingleOrDefault();
            if (SearchData != null)
            {
                return Json(1);
            }
            else
            {
                return Json(0);
            }
        }
        // GET: EmployeesManagment/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Employee employee = db.Employee.Find(id);
                if (employee == null)
                {
                    return HttpNotFound();
                }
                return View(employee);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // GET: EmployeesManagment/Create
        public ActionResult Create()
        {
            Employee emp = new Employee();
            if (Session["AdminId"] != null)
            {
                ViewBag.DepartmentId = new SelectList(db.Department, "DepartmentId", "DepartmentName");
                var LastEmployee = db.Employee.OrderByDescending(x => x.EmployeeId).FirstOrDefault();
                if (LastEmployee == null)
                {
                    emp.username = "empid@1";
                }
                else
                {
                    emp.username = "empid@" + (LastEmployee.EmployeeId + 1).ToString();
                }

                return View(emp);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,FirstName,LastName,DateOFBirth,Gender,Address,Mobile,DepartmentId,username,Password,EmpSalary")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employee.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(db.Department, "DepartmentId", "DepartmentName", employee.DepartmentId);
            return View(employee);
        }

        // GET: EmployeesManagment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Employee employee = db.Employee.Find(id);
                if (employee == null)
                {
                    return HttpNotFound();
                }
                ViewBag.DepartmentId = new SelectList(db.Department, "DepartmentId", "DepartmentName", employee.DepartmentId);
                return View(employee);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,FirstName,LastName,DateOFBirth,Gender,Address,Mobile,DepartmentId,username,Password,EmpSalary")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DepartmentId = new SelectList(db.Department, "DepartmentId", "DepartmentName", employee.DepartmentId);
            return View(employee);
        }

        // GET: EmployeesManagment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["AdminId"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Employee employee = db.Employee.Find(id);
                if (employee == null)
                {
                    return HttpNotFound();
                }
                return View(employee);
            }
            else
            {
                return HttpNotFound("Please Login Your Account and Try Again");
            }
        }

        // POST: EmployeesManagment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employee.Find(id);
            db.Employee.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/EmployeesManagment/Create.cshtml
@model HumanResourceManagementSystem.Models.Employee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/editform.css" rel="stylesheet" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<div class="main-content">
    <div class="container-fluid content-top-gap">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/EmployeesManagment/Index" style="color:darkblue">Employees</a></li>
                <li class="breadcrumb-item active" aria-current="page">Add-Employee</li>
            </ol>
        </nav>
    </div>
    <div class="form-block">
        <h2> Adding Employee Information</h2>
        @using (Html.BeginForm("Create", "EmployeesManagment", FormMethod.Post, new { name = "Eployeeadding", id = "Eployeeadding" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <section>
                <div class="container">
                    <div class="contacts12-main">
                        <!-- ....................... form ...................-->
                        <form action="" method="post" class="form">
                            <div class="main-input">

                                <div>
                                    @Html.LabelFor(model => model.username, "UniqueID", new { @class = "control-label col-md-2" })
                                    @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "contact-input", @readOnly = "readOnly" } })
                                    @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="text" name="FirstName" id="Name" onkeyup="myFunction()" placeholder="Enter First Name" class="contact-input" data-val="true"
                                           data-val-required="First Name is Blank" data-val-regex-pattern="^[a-zA-Z ]{2,30}$" data-val-regex="Please Enter Valid Name" data-val-minlength-min="3" data-val-minlength="Frist Name is Too Small" data-val-maxlength-max="20" data-val-maxlength="Frist Name is Too Large" />
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

                                </div>
                                <div class="input-icon position-relative">
                                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="text" name="LastName" id="LName" placeholder="Enter Last Name"
                                           onkeyup="uperFunction()" class="contact-input" data-val="true"
                                           data-val-required=" Last Name is Blank" data-val-regex-pattern="^[a-zA-Z ]{2,30}$" data-val-regex="Please Enter Valid Name" data-val-minlength-min="3" data-val-minlength="Last Name is Too Small" data-val-maxlength-max="20" data-val-maxlength="Last Name is Too Large" />
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>

                            </div>
                            <div class="main-input">
                                <div>
                                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="password" name="Password" id="Password" onchange="UserCheck()" placeholder="Enter Password" class="contact-input" data-val="true" data-val-required=" Password Field is Blank"
                                           data-val-regex-pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$" data-val-regex=" Minimum 8 character & one special character" data-val-maxlength-max="15" data-val-maxlength="Password Length is Max 15 or equal" />
                                    @*<span class="input-group-addon"><img id="Showbtn" src="~/images/showpassicon.png" /></span>*@
                                    <p id="Status"></p>
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>

                                <div>
                                    @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="tel" name="Mobile" id="Mobile" placeholder="Enter Mobile Number" onchange="Check()" class="contact-input" data-val="true" data-val-required=" Contact Field is Blank"
                                           data-val-regex-pattern="^(\+92|0|92)[0-9]{10}$" data-val-regex="Please use Valid pattren(+92/03)" />
                                    <p id="CheckMobile"></p>
                                    @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.DateOFBirth, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="date" name="DateOFBirth" id="datecheck" placeholder="" class="contact-input" min="1997-10-07" max="2004-10-07" value="2004-10-07" 
                                           data-val="true" data-val-required="Data of birth is Blank" />
                                    
                                    @Html.ValidationMessageFor(model => model.DateOFBirth, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="main-input2">

                                <div>
                                    @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DropDownList("DepartmentId", null, "...Department Name...", new { @class = "contact-input", @required = "required" })
                                    @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    @Html.LabelFor(model => model.EmpSalary, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <input type="number" name="EmpSalary" id="EmpSalary" placeholder="Total Salary" class="contact-input" data-val="true" data-val-required="Salary is  Blank" value="false" min="0" max="500000" />
                                    @Html.ValidationMessageFor(model => model.EmpSalary, "", new { @class = "text-danger" })
                                </div>
                                <div>
                                    <label style="font-size:14px medium; font-weight:600;">Male  : </label>
                                    @Html.RadioButtonFor(m => m.Gender, "Male")&nbsp;&nbsp;&nbsp;&nbsp;
                                    <label style="font-size:14px medium; font-weight:600;">Female :</label>
                                    @Html.RadioButtonFor(m => m.Gender, "Female")
                                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                            <textarea class="contact-textarea" name="Address" id="Address"
                                      placeholder="Type Address here" data-val="true" data-val-required="Street Adress is Blank" data-val-regex-pattern="^[#.0-9a-zA-Z\s,-]+$" data-val-regex="Please use this pattren(#1, North Street, Chennai - 11) " data-val-minlength-min="20" data-val-minlength="Street Adress is MiniMum 20"
                                      data-val-maxlength-max="100" data-val-maxlength="Street Adress is Too Large"></textarea>
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" id="AddEmployee" value="Add Employee" class="btn btn-default" />
                                    <i class="fa fa-arrow-circle-o-left">&nbsp;@Html.ActionLink("Back to List", "Index")</i>
                                </div>
                            </div>
                        </form>
                        <!-- //............. form ...................-->
                    </div>
                </div>
            </section>
        }
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
<script>
    $('#DateOFBirth').datepicker({
        endDate: '-18y'
    });
</script>

<!--- ..........................uper function  in Name ................-->
<script>
    function myFunction() {
        var x = document.getElementById("Name");
        x.value = x.value.toUpperCase();
    }
</script>
<script>
    function uperFunction() {
        var x = document.getElementById("LName");
        x.value = x.value.toUpperCase();
    }
</script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/js/Show.js"></script>


<!-- //............. Password Already Exist ...................-->
<script>
        function UserCheck() {
            $("#Status").html("Checking.........!");
            $.post("@Url.Action("Checkexist", "EmployeesManagment")",
                {
                    userdata: $("#Password").val()
                },
                function (data) {

                    if (data == 0) {
                        $("#Status").html('<font color="Green"> Password Available......!</font>');
                        $("#Password").css("border-color", "Green");
                    }
                    else {
                        $("#Status").html('<font color="Red"> That Password already taken......!</font>');
                        $("#Password").css("border-color", "Red");
                    }
                });
        }
</script>
<!-- //............. Mobile Already Exist ...................-->
<script>
        function Check() {
            $("#CheckMobile").html("Checking.........!");
            $.post("@Url.Action("Exsitinput", "EmployeesManagment")",
                {
                    mobiledata: $("#Mobile").val()
                },
                function (data) {
                    if (data == 0) {
                        $("#CheckMobile").html('<font color="Green"> Mobile Number Available......!</font>');
                        $("#Mobile").css("border-color", "Green");
                    }
                    else {
                        $("#CheckMobile").html('<font color="Red"> That Mobile Number already taken......!</font>');
                        $("#Mobile").css("border-color", "Red");
                    }
                });
        }
</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@section Validation {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/EmployeesManagment/Delete.cshtml
@model HumanResourceManagementSystem.Models.Employee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css/deleteemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/attendance/index" style="color:darkblue">Attendance</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete-Attendance</li>
            </ol>
        </nav>

    </div>


    <div class="dl-horizontal">
        <h2>Delete Employee</h2>
        <h3>Are you sure you want to delete this?</h3>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DateOFBirth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateOFBirth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EmpSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmpSalary)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Mobile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mobile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Department.DepartmentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Department.DepartmentName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>



        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                <i class="fa fa-arrow-circle-o-left"> &nbsp;@Html.ActionLink("Back to List", "Index")</i>
            </div>
            <label class="permission">*** You don't have any Permission to Dismiss an Employee ***</label>
        }
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/js/Show.js"></script>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/EmployeesManagment/Details.cshtml
@model HumanResourceManagementSystem.Models.Employee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css/detailemployee.css" rel="stylesheet" />
<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/EmployeesManagment/index" style="color:darkblue">Employees</a></li>
                <li class="breadcrumb-item active" aria-current="page">Detail-Employee</li>
            </ol>
        </nav>

    </div>
    <div class="dl-horizontal">
        <h2>Details Employee</h2>
        <h4>Employee Information</h4>
        <dl>
            <dt>
                @Html.DisplayNameFor(model => model.username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.username)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Password)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Password)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateOFBirth)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateOFBirth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.EmpSalary)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmpSalary)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Mobile)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mobile)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Department.DepartmentName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Department.DepartmentName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>




        </dl>
        <p class="btn-default">
            <i class="fa fa-pencil-square-o"> &nbsp;@Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeId })</i>
            <i class="fa fa-arrow-circle-o-left">&nbsp; @Html.ActionLink("Back to List", "Index")</i>
        </p>
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/js/Show.js"></script>

HumanResourceManagementSystem/HumanResourceManagementSystem/Views/EmployeesManagment/Index.cshtml
@model IEnumerable<HumanResourceManagementSystem.Models.Employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css/employeeindex.css" rel="stylesheet" />

<div class="main-content">
    <div class="container-fluid content-top-gap">

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb my-breadcrumb">
                <li class="breadcrumb-item"><a href="~/Admin/Dashboard" style="color:darkblue">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Employees-List</li>
            </ol>
        </nav>
    </div>

    <div class="info">
        <h2>Employees Information List</h2>
        <div style="height: auto; overflow-y: scroll">


            <a href="~/EmployeesManagment/List"  style="padding: 10px; color: blue;  " class="report">Generate Report<i class="fa fa-arrow-right"></i></a>



            <table class="table" id="Employeedata">
                <tr>
                    <th>
                        User Name
                    </th>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Password
                    </th>

                    <th>
                        Date OF Birth
                    </th>
                    <th>
                        Gender
                    </th>
                    <th>
                        Employee Salary
                    </th>
                    <th>
                        Mobile
                    </th>
                    <th>
                        Department Name
                    </th>
                    <th>
                        Address
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Password)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateOFBirth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EmpSalary)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mobile)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Department.DepartmentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>

                        <td>
                            @Html.ActionLink(".", "Edit", new { id = item.EmployeeId }, new { @class = " fa fa-pencil" })
                            @Html.ActionLink(".", "Details", new { id = item.EmployeeId }, new { @class = " fa fa-eye" })
                            @Html.ActionLink(".", "Delete", new { id = item.EmployeeId }, new { @class = " fa fa-trash" })
                        </td>
                    </tr>
                }

            </table>

            <a href="~/EmployeesManagment/List"  style="padding: 10px; color: blue;  " class="report">Generate Report<i class="fa fa-arrow-right"></i></a>
        </div>
    </div>
</div>


@*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/js/Show.js"></script>*@